import fs from 'fs';
import path from 'path';
import { toCamelCase } from './method-naming.js';

export const generateBaseFile = (services: string[], testsDir: string) => {
    const outputPath = path.resolve(process.cwd(), testsDir);
    if (!fs.existsSync(outputPath)) fs.mkdirSync(outputPath, { recursive: true });

    let imports = `// This file was auto-generated by playwright-service-generator

import { test as base } from '@playwright/test';\n`;
    imports += services.map(s => `import { ${s} } from '../services/${s}.js';`).join('\n') + '\n\n';

    let fixturesType = `type MyFixtures = {\n`;
    fixturesType += services.map(s => `  ${toCamelCase(s)}: ${s};`).join('\n');
    fixturesType += `\n};\n\n`;

    let extendBlock = `export const test = base.extend<MyFixtures>({\n`;
    extendBlock += services.map(s =>
        `  ${toCamelCase(s)}: async ({ request }, use) => {\n    const service = new ${s}(request);\n    await use(service);\n  }`
    ).join(',\n');
    extendBlock += `\n});\n\n`;

    extendBlock += `export { expect } from '@playwright/test';\n`;

    const content = imports + fixturesType + extendBlock;
    fs.writeFileSync(path.join(outputPath, 'base.ts'), content, 'utf8');
}

export const generateSkeletonTest = (testsDir: string) => {
    const outputPath = path.resolve(process.cwd(), testsDir);
    if (!fs.existsSync(outputPath)) fs.mkdirSync(outputPath, { recursive: true });

    const content = `// This file was auto-generated by playwright-service-generator

import { test, expect } from './base';

test('Creating and updating a person should be successful', { tag: ['@smoke'] }, async ({ request }) => {
  // Start creating tests here 
  expect(true).toBe(true);
});
`;

    fs.writeFileSync(path.join(outputPath, 'skeleton-test.ts'), content, 'utf8');
}
